### ISSUE TITLE
Error with frame extraction

### ISSUE THREAD

**Issue by StanHR** [chexov/image2pipe#1]
Here is the error message I received:

DEBUG:image2pipe.ffmpeg:popen ffmpeg -v error -ss 00:00:00 -i a.mp4 -an -sn -f image2pipe -vcodec rawvideo -pix_fmt bgr24 -vf fps=30,scale=400x400 -
Traceback (most recent call last):
  File ".\frame_extraction.py", line 45, in <module>
    decoder.start()
  File "C:\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'images_from_url.<locals>.<lambda>'
PS C:\Users\g_host\Desktop\dtoxd_GUI\wxTest> av_interleaved_write_frame(): Invalid argument
Error writing trailer of pipe:: Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Python36\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect

**Comment by chexov** [comment]
@StanHR Did you tried to run ffmpeg command and check if ffmpeg actually returning rawvideo?
`ffmpeg -v error -ss 00:00:00 -i a.mp4 -an -sn -f image2pipe -vcodec rawvideo -pix_fmt bgr24 -vf fps=30,scale=400x400 out.raw`

@StanHR Do you have steps to reproduce for this issue? Please attach test script which end with this error. Thanks

**Comment by chexov** [comment]
please make sure you have ffmpeg v4 @StanHR

**Comment by chexov** [comment]
closed due to inactivity
